# docs/source/examples/run_space_floats.yaml
# Run space (local): FloatValueDataSource -> FloatAddOperation -> FloatMultiplyOperation -> FloatValueProbe -> FloatTxtFileSaver
# Each block expands context keys (`value`, `addend`, `factor`) which downstream nodes bind from context automatically.

extensions: ["semantiva-examples"]

run_space:
  blocks:
    - mode: by_position
      context:
        value:  [1.0,  2.0,  3.5]
        addend: [1.0,  1.0,  1.0]
        factor: [10.0, 20.0, 30.0]

trace:
  driver: jsonl
  options:
    detail: all
  output_path: ./ser/

pipeline:
  nodes:
    - processor: FloatValueDataSource
    - processor: FloatAddOperation
    - processor: FloatMultiplyOperation
    - processor: FloatCollectValueProbe
      context_key: "result"
    - processor: template:"{value}_plus_{addend}_times_{factor}_equals_{result}.txt":path
    - processor: FloatTxtFileSaver
