name: SBOM and License Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project + tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # Pin to a recent, documented version of the CycloneDX Python tool
          pip install 'cyclonedx-bom==7.1.0' pip-licenses

      - name: Generate SBOM (CycloneDX JSON from environment)
        run: |
          # Use explicit subcommand; module invocation avoids PATH issues
          python -m cyclonedx_py environment \
            --output-file sbom.json \
            --output-format JSON

      - name: License Report
        run: |
          pip-licenses --format=json --output-file=licenses.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: semantiva-sbom
          path: |
            sbom.json
            licenses.json
