name: SBOM and License Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install cyclonedx-bom cyclonedx-python-lib pip-licenses

      - name: Generate SBOM (CycloneDX)
        run: |
          pip install -e .
          cyclonedx-py -o sbom.json || cyclonedx-bom -o sbom.json

      - name: License Report
        run: |
          pip-licenses --format=json --output-file=licenses.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: semantiva-sbom
          path: |
            sbom.json
            licenses.json
